package minicpbp.search;

import java.util.LinkedList;
import java.util.List;
import java.util.function.Predicate;

import minicpbp.util.Procedure;
import minicpbp.util.TraceLog;
import minicpbp.engine.core.IntVar;

/**
 * Common machinery for search strategies: solution / failure listener
 * registration, search-context state (current node id, parent, depth, branch
 * position), and the bookkeeping helpers {@link #withinNode(Procedure)} and
 * {@link #withinBranch(int, int, Procedure)} that subclasses use to wrap
 * their recursive search bodies.
 *
 * Subclasses (e.g. {@link DFSearch}, {@link LDSearch}) own the recursion
 * structure itself; this class owns the protocol used to observe it.
 *
 * Per-node / per-branch trace events are emitted directly to
 * {@link TraceLog}; solution / failure events are emitted alongside the
 * user-registered listeners in {@link #notifySolution()} and
 * {@link #notifyFailure()}.
 */
public abstract class Search {

	protected final List<Procedure> solutionListeners = new LinkedList<Procedure>();
	protected final List<Procedure> failureListeners  = new LinkedList<Procedure>();

	protected long nextNodeId          = 0;
	protected long currentNodeId       = -1;
	protected long currentParentNodeId = -1;
	protected int  currentDepth        = -1;
	protected int  currentBranchIndex  = -1;
	protected int  currentBranchTotal  =  0;

	/**
	 * Adds a listener that is called on each solution.
	 *
	 * @param listener the closure to be called whenever a solution is found
	 */
	public void onSolution(Procedure listener) {
		solutionListeners.add(listener);
	}

	/**
	 * Adds a listener that is called whenever a failure occurs and the search
	 * backtracks. This happens when an
	 * {@link minicpbp.util.exception.InconsistencyException} is thrown when
	 * executing the closure generated by the branching.
	 *
	 * @param listener the closure to be called on each failure
	 */
	public void onFailure(Procedure listener) {
		failureListeners.add(listener);
	}

	/**
	 * @return the id of the node currently being explored, or -1 outside the
	 *         search. Node ids are monotonic and unique within this Search
	 *         instance across calls to {@code solve()} and restart iterations.
	 */
	public long currentNodeId() {
		return currentNodeId;
	}

	/**
	 * @return the id of the parent of the current node, or -1 if the current
	 *         node is a search root (top of {@code solve()} or a restart).
	 */
	public long currentParentNodeId() {
		return currentParentNodeId;
	}

	/**
	 * @return the depth of the current node (root is 0), or -1 outside the
	 *         search.
	 */
	public int currentDepth() {
		return currentDepth;
	}

	/**
	 * @return the index of the branch currently being executed at the current
	 *         node. Valid between the {@code TraceLog.branch} emission and the
	 *         matching {@code TraceLog.branchReturn} / failure; undefined
	 *         elsewhere.
	 */
	public int currentBranchIndex() {
		return currentBranchIndex;
	}

	/**
	 * @return the total number of branches at the current node. Valid in the
	 *         same window as {@link #currentBranchIndex()}.
	 */
	public int currentBranchTotal() {
		return currentBranchTotal;
	}

	protected void notifySolution() {
		TraceLog.solution(currentNodeId);
		solutionListeners.forEach(Procedure::call);
	}

	protected void notifyFailure() {
		TraceLog.failure(currentNodeId);
		failureListeners.forEach(Procedure::call);
	}

	/**
	 * Runs {@code body} as the exploration of one search node: assigns this
	 * node a fresh id, records the parent and depth, emits a node-enter trace
	 * frame before and a node-exit trace frame after. The previous context is
	 * restored on exit, including when {@code body} throws (so a
	 * {@link StopSearchException} or other escape does not leak stale state
	 * into the next root).
	 */
	protected void withinNode(Procedure body) {
		long savedNodeId       = currentNodeId;
		long savedParentNodeId = currentParentNodeId;
		int  savedDepth        = currentDepth;
		currentParentNodeId = currentNodeId;
		currentNodeId       = nextNodeId++;
		currentDepth        = savedDepth + 1;
		try {
			TraceLog.nodeEnter(currentNodeId, currentParentNodeId, currentDepth);
			body.call();
			TraceLog.nodeExit(currentNodeId, currentParentNodeId, currentDepth);
		} finally {
			currentNodeId       = savedNodeId;
			currentParentNodeId = savedParentNodeId;
			currentDepth        = savedDepth;
		}
	}

	/**
	 * Runs {@code body} as the exploration of one branch from the current
	 * node. Sets {@link #currentBranchIndex()} / {@link #currentBranchTotal()},
	 * emits a branch-taken trace frame before, and emits a branch-return frame
	 * only if {@code body} returns normally (an exception propagates out and
	 * is the caller's responsibility — this is how the failure edge stays the
	 * caller's catch block).
	 */
	protected void withinBranch(int branchIndex, int branchTotal, Procedure body) {
		currentBranchIndex = branchIndex;
		currentBranchTotal = branchTotal;
		TraceLog.branch(currentNodeId, currentBranchIndex, currentBranchTotal);
		body.call();
		currentBranchIndex = branchIndex;
		currentBranchTotal = branchTotal;
		TraceLog.branchReturn(currentNodeId, currentBranchIndex, currentBranchTotal);
	}

	public abstract SearchStatistics solve(Predicate<SearchStatistics> limit);

	public abstract SearchStatistics optimize(Objective obj, Predicate<SearchStatistics> limit);

	public abstract SearchStatistics solveRestarts(Predicate<SearchStatistics> limit, int nbFailCutof, double restartFactor);

	public abstract void initializeImpact(IntVar... x);

	public abstract void initializeImpactDomains(IntVar... x);
}
